//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySwoleMate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout()
        {
            this.Trainees = new HashSet<Trainee>();
        }
    
        public int WorkoutID { get; set; }
        public string WorkoutName { get; set; }
        public string Exercise1 { get; set; }
        public decimal Exercise1Reps { get; set; }
        public decimal Exercise1Sets { get; set; }
        public string Exercise2 { get; set; }
        public decimal Exercise2Reps { get; set; }
        public decimal Exercise2Sets { get; set; }
        public string Exercise3 { get; set; }
        public decimal Exercise3Reps { get; set; }
        public decimal Exercise3Sets { get; set; }
        public string Exercise4 { get; set; }
        public decimal Exercise4Reps { get; set; }
        public decimal Exercise4Sets { get; set; }
        public string Exercise5 { get; set; }
        public decimal Exercise5Reps { get; set; }
        public decimal Exercise5Sets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee> Trainees { get; set; }
    }
}
